#!/usr/bin/env python3
"""Generate an implement packet scaffold plus response-contract outputs."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import jsonschema

SKILL_DIR = Path(__file__).resolve().parent.parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--objective', required=True, help='Execution objective statement.')
    parser.add_argument('--contract-root', default='.', help='Root containing the contract layer.')
    parser.add_argument('--parent-issue', default='', help='Parent issue URL/ID.')
    parser.add_argument('--request-id', default='req-0001', help='Request identifier.')
    parser.add_argument('--response-id', default='resp-0001', help='Response identifier.')
    parser.add_argument('--reviewed-head', default='0'*40, help='40-char reviewed head commit.')
    parser.add_argument('--reviewed-short', default='0'*7, help='7-12 char reviewed head short ref.')
    parser.add_argument('--template', default='assets/IMPLEMENT.packet.template.md', help='Template path.')
    parser.add_argument('--out', default=None, help='Output path. Defaults to $WT/IMPLEMENT/IMPLEMENT.md when WT is set; otherwise IMPLEMENT.md.')
    parser.add_argument('--wt', default=None, help='Integration worktree path. Falls back to env WT when unset.')
    parser.add_argument('--force', action='store_true', help='Overwrite output file if it already exists.')
    return parser.parse_args()


def render(template_text: str, objective: str, parent_issue: str) -> str:
    seeded = template_text.replace('<objective>', objective)
    if parent_issue:
        seeded = seeded.replace('- Parent plan issue:', f'- Parent plan issue: {parent_issue}', 1)
    return '\n'.join([
        '<!-- generated by skills/implement/scripts/generate_implement_packet.py -->',
        f'<!-- objective: {objective} -->',
        '',
        seeded,
    ])


def validate_json(instance: dict, schema_path: Path) -> list[str]:
    schema = json.loads(schema_path.read_text(encoding='utf-8'))
    resolver = jsonschema.validators.RefResolver(base_uri=schema_path.resolve().as_uri(), referrer=schema)
    validator = jsonschema.Draft202012Validator(schema, resolver=resolver)
    return [e.message for e in validator.iter_errors(instance)]


def main() -> int:
    args = parse_args()
    wt = Path(args.wt or os.environ.get('WT') or '.').expanduser().resolve()
    contract_root = Path(args.contract_root).expanduser().resolve()
    template_path = Path(args.template).expanduser()
    if not template_path.is_absolute():
        template_path = (SKILL_DIR / template_path).resolve()
    out_path = Path(args.out).expanduser().resolve() if args.out else (wt / 'IMPLEMENT' / 'IMPLEMENT.md')
    if out_path.exists() and not args.force:
        raise SystemExit(f'output already exists: {out_path} (use --force)')
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(template_path.read_text(encoding='utf-8'), args.objective, args.parent_issue), encoding='utf-8')

    meta_path = out_path.with_name('packet.meta.json')
    meta_payload = {
        'kind': 'implement.packet.meta.v2',
        'objective': args.objective,
        'parent_issue': args.parent_issue,
        'wt': str(wt),
        'contract_root': str(contract_root),
        'packet_path': str(out_path),
    }
    meta_path.write_text(json.dumps(meta_payload, indent=2) + '\n', encoding='utf-8')

    response_instance = {
        'kind': 'review_response.v1',
        'review_request_id': args.request_id,
        'reviewed_head': {'commit': args.reviewed_head, 'short': args.reviewed_short, 'subject': args.objective},
        'review_scope': {
            'basis': 'bounded batch execution under merged contract layer',
            'inputs': ['PLAN/request.instance.json', 'PLAN/contract.bindings.json', 'IMPLEMENT/IMPLEMENT.md'],
            'limitation': 'initial scaffold; findings and next patch set require runtime execution evidence'
        },
        'verdict': {'status': 'PENDING', 'summary': 'execution scaffold emitted; evidence not yet evaluated'},
        'findings': [],
        'next_patch_set': []
    }
    response_instance_path = out_path.with_name('response.instance.json')
    response_instance_path.write_text(json.dumps(response_instance, indent=2) + '\n', encoding='utf-8')

    response_manifest = {
        '@context': 'context/plan-review-loop.context.jsonld',
        '@id': f'repo:implement/{args.response_id}',
        '@type': 'ResponseManifest',
        'kind': 'response_manifest.v1',
        'response_id': args.response_id,
        'request_ref': 'PLAN/request.instance.json',
        'scope_root': str(wt),
        'canonical_artifact': 'IMPLEMENT/response.instance.json',
        'derived_views': ['IMPLEMENT/IMPLEMENT.md'],
        'bundle': {
            'kind': 'bundle_envelope.v1',
            'bundle_role': 'response',
            'archive_format': 'tar_gz',
            'archive_name': 'response.bundle.tar.gz',
            'contents': [
                {'path': 'IMPLEMENT/response.instance.json', 'role': 'canonical_response'},
                {'path': 'IMPLEMENT/IMPLEMENT.md', 'role': 'derived_view'},
                {'path': 'IMPLEMENT/response.validation.json', 'role': 'validation_report'}
            ]
        },
        'verdict_ref': 'IMPLEMENT/response.instance.json#/verdict',
        'findings_ref': 'IMPLEMENT/response.instance.json#/findings'
    }
    response_manifest_path = out_path.with_name('response.manifest.json')
    response_manifest_path.write_text(json.dumps(response_manifest, indent=2) + '\n', encoding='utf-8')

    response_validation = {
        'kind': 'response_validation.v1',
        'canonical_response_ref': 'IMPLEMENT/response.instance.json',
        'response_manifest_ref': 'IMPLEMENT/response.manifest.json',
        'canonical_response_valid': not validate_json(response_instance, contract_root / 'schemas/review_response.schema.json'),
        'response_manifest_valid': not validate_json(response_manifest, contract_root / 'schemas/response.schema.json'),
        'errors': {
            'canonical_response': validate_json(response_instance, contract_root / 'schemas/review_response.schema.json'),
            'response_manifest': validate_json(response_manifest, contract_root / 'schemas/response.schema.json'),
        }
    }
    (out_path.with_name('response.validation.json')).write_text(json.dumps(response_validation, indent=2) + '\n', encoding='utf-8')
    print(out_path)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
