#!/usr/bin/env python3
"""Generate a git-flow-aware plan packet scaffold plus request/batch contract outputs."""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import jsonschema

SKILL_DIR = Path(__file__).resolve().parent.parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--objective', required=True, help='Primary objective statement.')
    parser.add_argument('--failure', default='', help='Failure signature or problem shorthand.')
    parser.add_argument('--contract-root', default='.', help='Root containing the contract layer.')
    parser.add_argument('--request-id', default='req-0001', help='Request identifier.')
    parser.add_argument('--reviewed-head', default='0'*40, help='40-char reviewed head commit.')
    parser.add_argument('--reviewed-short', default='0'*7, help='7-12 char reviewed head short ref.')
    parser.add_argument('--bounded-batch-id', default='batch-0001', help='Bounded batch identifier.')
    parser.add_argument('--target-layer', default='implementation', choices=['contract', 'shell', 'implementation'], help='Target layer for the bounded batch.')
    parser.add_argument('--target-branch', default='main', help='Target branch.')
    parser.add_argument('--integration-worktree-id', default='iwt-0001', help='Integration worktree identifier.')
    parser.add_argument('--mode', default='full', choices=['full', 'body'], help='Retained for compatibility.')
    parser.add_argument('--template', default='assets/README.plan.template.md', help='Template path.')
    parser.add_argument('--out', default=None, help='Output path for generated packet. Defaults to $WT/PLAN/README.md when WT is set; otherwise README.md.')
    parser.add_argument('--wt', default=None, help='Integration worktree path. Falls back to env WT when unset.')
    parser.add_argument('--force', action='store_true', help='Overwrite output file if it already exists.')
    return parser.parse_args()


def render(template_text: str, args: argparse.Namespace, wt: Path, contract_root: Path) -> str:
    replacements = {
        '<objective>': args.objective,
        '<failure>': args.failure or 'none recorded yet',
        '<bounded_batch_id>': args.bounded_batch_id,
        '<target_layer>': args.target_layer,
        '<target_branch>': args.target_branch,
        '<integration_worktree_id>': args.integration_worktree_id,
        '<contract_root>': str(contract_root),
        '<worktree_path>': str(wt),
    }
    text = template_text
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return '\n'.join([
        '<!-- generated by skills/plan/scripts/generate_plan_packet.py -->',
        f'<!-- objective: {args.objective} -->',
        '',
        text,
    ])


def validate_json(instance: dict, schema_path: Path) -> list[str]:
    schema = json.loads(schema_path.read_text(encoding='utf-8'))
    resolver = jsonschema.validators.RefResolver(base_uri=schema_path.resolve().as_uri(), referrer=schema)
    validator = jsonschema.Draft202012Validator(schema, resolver=resolver)
    return [e.message for e in validator.iter_errors(instance)]


def main() -> int:
    args = parse_args()
    wt = Path(args.wt or os.environ.get('WT') or '.').expanduser().resolve()
    contract_root = Path(args.contract_root).expanduser().resolve()
    template_path = Path(args.template).expanduser()
    if not template_path.is_absolute():
        template_path = (SKILL_DIR / template_path).resolve()

    out_path = Path(args.out).expanduser().resolve() if args.out else (wt / 'PLAN' / 'README.md')
    if out_path.exists() and not args.force:
        raise SystemExit(f'output already exists: {out_path} (use --force)')
    out_path.parent.mkdir(parents=True, exist_ok=True)

    template_text = template_path.read_text(encoding='utf-8')
    out_path.write_text(render(template_text, args, wt, contract_root), encoding='utf-8')

    packet_meta = {
        'kind': 'plan.packet.meta.v2',
        'objective': args.objective,
        'failure': args.failure,
        'wt': str(wt),
        'contract_root': str(contract_root),
        'bounded_batch_id': args.bounded_batch_id,
        'target_layer': args.target_layer,
        'target_branch': args.target_branch,
        'integration_worktree_id': args.integration_worktree_id,
        'packet_path': str(out_path),
    }
    (out_path.with_name('packet.meta.json')).write_text(json.dumps(packet_meta, indent=2) + '\n', encoding='utf-8')

    bindings = {
        'kind': 'contract_bindings.v1',
        'contract_root': str(contract_root),
        'context_ref': 'context/plan-review-loop.context.jsonld',
        'anchor_registry_ref': 'anchors/anchor_registry.bootstrap.json',
        'request_schema_ref': 'schemas/request.schema.json',
        'response_schema_ref': 'schemas/response.schema.json',
        'review_response_schema_ref': 'schemas/review_response.schema.json',
        'archive_envelope_schema_ref': 'schemas/archive_envelope.schema.json',
        'response_to_next_request_schema_ref': 'schemas/response_to_next_request.schema.json',
        'handoff_contract_ref': 'skills/loop/assets/handoff.contract.json',
        'git_flow_manifest_ref': 'control/git-flow/git_flow.manifest.json',
        'batch_manifest_schema_ref': 'schemas/batch_manifest.schema.json',
        'integration_gate_plan_schema_ref': 'schemas/integration_gate_plan.schema.json',
        'promotion_plan_schema_ref': 'schemas/promotion_plan.schema.json',
        'prompt_registry_ref': 'prompt-registry/manifest.json',
        'notes': 'git-flow-aware plan bindings'
    }
    bindings_path = out_path.with_name('contract.bindings.json')
    bindings_path.write_text(json.dumps(bindings, indent=2) + '\n', encoding='utf-8')

    request_instance = {
        '@context': 'context/plan-review-loop.context.jsonld',
        '@id': f'repo:plan/{args.request_id}',
        '@type': 'RequestManifest',
        'kind': 'request_manifest.v1',
        'request_id': args.request_id,
        'scope_root': str(wt),
        'input_mode': 'head_plus_working_tree',
        'reviewed_head': {
            'commit': args.reviewed_head,
            'short': args.reviewed_short,
            'date': datetime.now(timezone.utc).isoformat(),
            'subject': args.objective,
        },
        'anchors': {
            'commit_ref': args.reviewed_head,
            'request_manifest_ref': 'PLAN/request.instance.json',
            'response_manifest_ref': 'IMPLEMENT/response.manifest.json',
            'git_log_ref': 'PLAN/request.git_log.json',
            'diff_ref': 'PLAN/request.diff'
        },
        'submitted_artifacts': [
            'PLAN/README.md',
            'PLAN/packet.meta.json',
            'PLAN/contract.bindings.json',
            'PLAN/batch.manifest.json',
            'PLAN/integration_gate.plan.json',
            'PLAN/promotion.plan.json'
        ],
        'bundle': {
            'kind': 'bundle_envelope.v1',
            'bundle_role': 'request',
            'archive_format': 'tar_gz',
            'archive_name': 'request.bundle.tar.gz',
            'contents': [
                {'path': 'PLAN/README.md', 'role': 'plan_packet'},
                {'path': 'PLAN/packet.meta.json', 'role': 'plan_meta'},
                {'path': 'PLAN/contract.bindings.json', 'role': 'contract_bindings'},
                {'path': 'PLAN/batch.manifest.json', 'role': 'bounded_batch_manifest'},
                {'path': 'PLAN/integration_gate.plan.json', 'role': 'integration_gate_plan'},
                {'path': 'PLAN/promotion.plan.json', 'role': 'promotion_plan'}
            ]
        },
        'expected_response': {
            'one_output_per_input': True,
            'canonical_response': 'IMPLEMENT/response.instance.json',
            'derived_views': ['IMPLEMENT/IMPLEMENT.md']
        },
        'working_tree': {
            'status': 'clean',
            'status_ref': 'PLAN/request.status.txt'
        }
    }
    request_path = out_path.with_name('request.instance.json')
    request_path.write_text(json.dumps(request_instance, indent=2) + '\n', encoding='utf-8')

    req_errors = validate_json(request_instance, contract_root / 'schemas/request.schema.json')
    request_validation = {
        'kind': 'request_validation.v1',
        'instance_ref': 'PLAN/request.instance.json',
        'schema_ref': 'schemas/request.schema.json',
        'valid': not req_errors,
        'errors': req_errors,
    }
    (out_path.with_name('request.validation.json')).write_text(json.dumps(request_validation, indent=2) + '\n', encoding='utf-8')

    batch_manifest = {
        'kind': 'bounded_batch_manifest.v1',
        'bounded_batch_id': args.bounded_batch_id,
        'target_layer': args.target_layer,
        'target_branch': args.target_branch,
        'integration_worktree_id': args.integration_worktree_id,
        'deliverables': ['request.instance.json', 'response.instance.json'],
        'integration_surface': 'one integration worktree per bounded batch'
    }
    (out_path.with_name('batch.manifest.json')).write_text(json.dumps(batch_manifest, indent=2) + '\n', encoding='utf-8')

    gate_plan = {
        'kind': 'integration_gate_plan.v1',
        'bounded_batch_id': args.bounded_batch_id,
        'runs_on': 'integration_worktree',
        'required_checks': ['authority_gate', 'contract_package_gate', 'artifact_conformance_gate'],
        'required_artifacts': ['PLAN/request.instance.json', 'PLAN/contract.bindings.json', 'IMPLEMENT/response.instance.json', 'IMPLEMENT/response.manifest.json'],
        'pass_effect': 'promotion_decision_can_pass',
        'fail_effect': 'bounded_batch_rejected_or_reworked'
    }
    (out_path.with_name('integration_gate.plan.json')).write_text(json.dumps(gate_plan, indent=2) + '\n', encoding='utf-8')

    promotion_plan = {
        'kind': 'promotion_plan.v1',
        'bounded_batch_id': args.bounded_batch_id,
        'promotion_mode': 'patch_promotion',
        'target_branch': args.target_branch,
        'required_evidence_refs': ['PLAN/request.validation.json', 'IMPLEMENT/response.validation.json'],
        'post_promotion_gates': ['main_authority_gate', 'main_contract_package_gate', 'main_artifact_conformance_gate'],
        'rollback_mode': 'retain_integration_worktree_and_reject_promotion'
    }
    (out_path.with_name('promotion.plan.json')).write_text(json.dumps(promotion_plan, indent=2) + '\n', encoding='utf-8')

    print(out_path)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
